name: phpstan

on:
  push:
    branches: [ "master" ]
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  schedule:
    - cron: '0 0 * * *'

jobs:
  package-phpstan:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          level: 4
          path: src/
